/* 
		[
			 '名称',
			 '性别[男/女/中性]',
			 '类型（力量/敏捷/能量/全能）',
			 '制服',
			 '种族',
			 '阵营',
				['能力1','能力2'],
				[
						{for:'队长技能使用对象',type:'属性1名称',value:'属性1的值' },
						{for:'队长技能使用对象',type:'属性2名称',value:'属性2的值' }
				],
				[
						{for:'非队长技能使用对象',type:'属性1名称',value:'属性1的值' },
						{for:'非队长技能使用对象',type:'属性2名称',value:'属性2的值' }
				],
				是否T3[t2-2/t3-3/t2.5-4]
		]
*/
const a = {
	a: '强大', b: '超级传感器', c: '精神', d: '治愈', e: '高速移动', f: '领导力', g: '灵活', h: '毒', i: '火焰', j: '冰冻', k: '电击', l: '魔法', m: '机器', n: '武器专家', o: '指挥', p: '耐久力', q: '特工',
	r: '邪恶', s: '精神抵抗', t: '共生体', u: '能源斗士', v: '凤凰之力', w: '混沌魔法', x: '蜘蛛感应', y: '冷血', z: '时间冷冻免疫', A: '神奇四侠', B: '邪恶六人组', C: '宇宙力量', D: '天临四将', E: '宇宙魔方',
	F: '伽玛射线', G: '黑暗复仇者', H: '永恒族', I: '捍卫者', J: '地狱火'
};
const g = {
	m: '男性', f: '女性', t: '中性'
}
const t = {
	p: '力量', f: '敏捷', e: '能量', a: '全能'
}
const s = {
	h: '英雄', f: '反派', z: '中立'
}
const b = {
	a: '人类', b: '变种人', c: '异人族', d: '外星人', e: '生物', f: '未知'
}
const d = {
	a: '所攻', b: '能攻', c: '物攻', d: '所防', e: '物防', f: '能防', g: '生命', h: '暴击', i: '异常状态时间', j: '无视回避', k: '技能冷却', l: '火攻伤害', m: '电击伤害', n: '回避', o: '精神伤害', p: '剧毒伤害', q: '冰冻伤害',
	r: '爆伤', s: '攻速', t: '速度', u: '无视防御', v: '减益效果效率增加至', w: '英雄增伤', x: '男性增伤', y: '首领类敌人增伤', z: '精神抗性', A: '火焰抗性', B: '电击抗性', C: '剧毒抗性', D: '属性伤害', E: '恢复', F: '英雄减伤',
	G: '反派增伤', H: '反派减伤', I: '技能增伤', J: '额外伤害量', K: '多段打击伤害', L: '多段打击伤害减少', M: '受到伤害减少', N: '物理反射减伤', O: '所有反射减伤', P: '免疫冰冻伤害', Q: '精神伤害免疫', R: '电击伤害免疫',
	S: '免疫灼烧效果', T: '免疫恐惧效果', U: '免疫出血效果', V: '免疫骨折效果', W: '异常状态时', X: '霸体', Z: '特殊'
}
const q = {
	a: '所有人', b: '召唤兽'
}
const z = {
	a: '现代',
	b: '经典',
	c: '全新，全异',
	d: '复仇者联盟',
	e: '复仇者联盟：奥创纪元',
	f: '复仇者联盟3：无限战争',
	g: '复仇者联盟4：终局之战',
	h: '复仇者队服',
	l: '复仇者联盟3099',
	i: '美国队长：复仇者先锋',
	j: '美国队长：冬兵',
	k: '美国队长：内战',
	m: '漫威新刊！',
	n: '隐秘战争：1602',
	o: '隐秘战争：1872',
	p: '隐秘战争：2099',
	q: '隐秘战争：不完美的未来',
	r: '隐秘战争：女复仇者联盟',
	s: '隐秘战争：惊奇队长&卡萝军团',
	t: '隐秘战争：无限',
	u: '隐秘战争：漫威僵尸',
	v: '隐秘战争：红骷髅',
	w: '隐秘战争：装甲战争',
	x: '隐秘战争：重申你的誓言',
	y: '隐秘战争：雷神们',
	z: '银河护卫队',
	A: '银河护卫队2',
	B: '漫威：雷神3：诸神黄昏',
	C: 'X特工队',
	D: '凤凰五人组',
	E: '未来基础智团',
	F: '天启纪元',
	G: '非凡复仇者',
	H: '电影：蚁人',
	I: '电影《蚁人2：黄蜂女现身》',
	J: '电影《黑寡妇》',
	K: '电影《黑寡妇》（飞雪套装）',
	L: '电影：黑豹',
	M: '电影《惊奇队长》',
	N: '无限',
	O: '无限合体',
	P: '蜘蛛侠：英雄远征',
	Q: '电影：奇异博士',
	R: '神盾局特工',
	S: '旺达幻视',
	T: '黑暗复仇者'
}

const heros = [
	['神奇先生', g.m, t.p, z.a, b.a, s.h, [a.p, a.f, a.A], [{ for: a.A, type: d.a, value: '65%' }], null, 3],
	['神奇先生', g.m, t.p, z.E, b.a, s.h, [a.p, a.f, a.A], [{ for: a.A, type: d.a, value: '65%' }], null, 3],
	['神奇先生', g.m, t.p, '制造者', b.a, s.f, [a.p, a.r, a.A], [{ for: a.A, type: d.a, value: '65%' }], null, 3],
	['石头人', g.m, t.p, z.a, b.a, s.h, [a.a, a.p, a.A], [{ for: q.a, type: d.d, value: '50%' }], [{ for: a.A, type: d.a, value: '40%' }, { for: a.A, type: d.N, value: '50%' }, { for: a.A, type: d.d, value: '5%' }], 4],
	['石头人', g.m, t.p, z.E, b.a, s.h, [a.a, a.p, a.A], [{ for: q.a, type: d.d, value: '50%' }], [{ for: q.a, type: d.g, value: '15%' }, { for: a.A, type: d.a, value: '40%' }, { for: a.A, type: d.N, value: '50%' }, { for: a.A, type: d.d, value: '5%' }], 4],
	['石头人', g.m, t.p, z.b, b.a, s.h, [a.a, a.p, a.A], [{ for: q.a, type: d.d, value: '50%' }], [{ for: q.a, type: d.g, value: '15%' }, { for: a.A, type: d.a, value: '40%' }, { for: a.A, type: d.N, value: '50%' }, { for: a.A, type: d.d, value: '25%' }, { for: a.A, type: d.y, value: '25%' }], 4],
	['浩克', g.m, t.p, z.d, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, z.q, b.a, s.f, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, '世界大战浩克', b.a, s.f, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, z.B, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, z.g, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, z.h, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['浩克', g.m, t.p, '不朽浩克', b.a, s.f, [a.F, a.p], [{ for: q.a, type: d.d, value: '24%' }], null, 3],
	['纳摩', g.m, t.p, z.b, b.b, s.h, [a.a, a.p], [{ for: q.a, type: d.h, value: '24%' }], null, 3],
	['纳摩', g.m, t.p, z.D, b.b, s.f, [a.a, a.p, a.v], [{ for: q.a, type: d.h, value: '24%' }], null, 3],
	['美国队长', g.m, t.p, z.d, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.e, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.f, t.p, z.p, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.j, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.k, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.m, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.f, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.g, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.h, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.p, z.l, b.a, s.h, [a.f, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['美国队长', g.m, t.e, '九头蛇首领', b.a, s.f, [a.E, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 3],
	['金刚狼', g.m, t.p, z.b, b.b, s.h, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 3],
	['金刚狼', g.m, t.p, z.F, b.b, s.h, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 3],
	['金刚狼', g.m, t.p, '全新漫威NOW！', b.b, s.h, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 3],
	['金刚狼', g.m, t.p, z.C, b.b, s.h, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 3],
	['金刚狼', g.m, t.p, 'X皇室', b.b, s.h, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 3],
	['黑豹', g.m, t.p, z.a, b.a, s.h, [a.g, a.o], [{ for: q.a, type: d.h, value: '15%' }], null, 3],
	['黑豹', g.m, t.p, z.k, b.a, s.h, [a.g, a.o], [{ for: q.a, type: d.h, value: '15%' }], null, 3],
	['黑豹', g.m, t.p, z.L, b.a, s.h, [a.g, a.o], [{ for: q.a, type: d.h, value: '15%' }], null, 3],
	['卢克·凯奇', g.m, t.p, z.a, b.a, s.h, [a.a, a.p, a.I], null, null, 4],
	['卢克·凯奇', g.m, t.p, z.c, b.a, s.h, [a.a, a.p, a.I], null, null, 4],
	['卢克·凯奇', g.m, t.p, '漫威影剧 卢克·凯奇', b.a, s.h, [a.a, a.p, a.I], null, null, 4],
	['卢克·凯奇', g.m, t.p, '城郊套装', b.a, s.h, [a.a, a.p, a.I], null, [{ for: a.I, type: d.j, value: '35%' }], 4],
	['战虎', g.m, t.p, z.a, b.a, s.h, [a.D, a.a, a.p,], [{ for: q.a, type: d.k, value: '24%' }], null, 4],
	['月光骑士', g.m, t.p, z.a, b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['月光骑士', g.m, t.p, '装甲', b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['月光骑士', g.m, t.p, '骑士先生', b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['浩克（阿玛迪斯·赵）', g.m, t.p, '绝妙青春浩克', b.a, s.h, [a.F, a.p], null, null, 4],
	['浩克（阿玛迪斯·赵）', g.m, t.p, '怪兽出笼！（MFF变体）', b.a, s.h, [a.F, a.p], null, null, 4],
	['浩克（阿玛迪斯·赵）', g.m, t.p, '膂力', b.a, s.h, [a.F, a.p], null, null, 4],
	['铁拳', g.m, t.p, z.b, b.a, s.h, [a.g, a.d, a.I], null, null, 4],
	['铁拳', g.m, t.p, '新复仇者', b.a, s.h, [a.g, a.d, a.I], null, null, 4],
	['铁拳', g.m, t.p, z.c, b.a, s.h, [a.g, a.d, a.I], null, null, 4],
	['铁拳', g.m, t.p, '漫威影剧：铁拳', b.a, s.h, [a.g, a.d, a.I], null, null, 4],
	['铁拳', g.m, t.p, '活体武器', b.a, s.h, [a.g, a.d, a.I], [{ for: a.I, type: d.a, value: '60%' }], null, 4],
	['阿瑞斯', g.m, t.p, z.a, b.d, s.h, [a.G, a.n, a.a], [{ for: q.a, type: d.c, value: '30%' }], null, 4],
	['上气', g.m, t.p, '摩登', b.a, s.h, [a.g, a.f], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['刀锋战士', g.m, t.p, z.a, b.a, s.h, [a.d, a.n], null, null, 2],
	['刀锋战士', g.m, t.p, '70年代古典', b.a, s.h, [a.d, a.n], null, null, 2],
	['刀锋战士', g.m, t.p, z.d, b.a, s.h, [a.d, a.n], null, null, 2],
	['制裁者', g.m, t.p, z.a, b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['制裁者', g.m, t.p, '黑暗', b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['制裁者', g.m, t.p, '战争之旅', b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['制裁者', g.m, t.p, '漫威影剧 夜魔侠', b.a, s.h, [a.f, a.n], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['制裁者', g.m, t.p, '漫威遗产', b.a, s.h, [a.f, a.n, a.m], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['制裁者', g.m, t.p, '宇宙恶灵骑士', b.a, s.f, [a.C, a.i], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['剑仙', g.m, t.p, z.a, b.a, s.h, [a.f, a.n], [{ for: s.h, type: d.d, value: '35%' }], null, 2],
	['反浩克装甲（钢铁侠装甲马克44）', g.m, t.p, z.e, b.e, s.h, [a.a, a.m], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['反浩克装甲（钢铁侠装甲马克44）', g.m, t.p, '重型护甲', b.e, s.h, [a.a, a.m], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['反浩克装甲（钢铁侠装甲马克44）', g.m, t.p, z.f, b.e, s.h, [a.a, a.m], [{ for: q.a, type: d.c, value: '24%' }], null, 2],
	['哥利亚巨人', g.m, t.p, z.b, b.a, s.h, [a.a, a.p], [{ for: q.a, type: d.c, value: '45%' }], null, 2],
	['小浩克', g.m, t.p, '新复仇者', b.d, s.h, [a.a, a.p], [{ for: q.a, type: d.e, value: '30%' }], null, 2],
	['巨人', g.m, t.p, z.a, b.a, s.h, [a.a], [{ for: q.a, type: d.g, value: '30%' }], null, 2],
	['巨人', g.m, t.p, '奥创皮姆', b.a, s.f, [a.a], [{ for: q.a, type: d.g, value: '30%' }], null, 2],
	['哥利亚巨人（巨人）', g.m, t.p, z.a, b.a, s.h, [a.a], [{ for: q.a, type: d.g, value: '30%' }], null, 2],
	['德拉克斯', g.m, t.p, z.z, b.d, s.h, [a.d], null, null, 2],
	['德拉克斯', g.m, t.p, z.c, b.d, s.h, [a.d], null, null, 2],
	['戈尔贡', g.m, t.p, '王者之战', b.c, s.h, [a.a], null, null, 2],
	['战途', g.m, t.p, z.C, b.b, s.h, [a.a, a.f], null, null, 2],
	['树人格鲁特', g.m, t.p, z.z, b.d, s.h, [a.d], [{ for: t.p, type: d.e, value: '45%' }], null, 2],
	['树人格鲁特', g.m, t.p, z.y, b.d, s.h, [a.d], [{ for: t.p, type: d.e, value: '45%' }], null, 2],
	['树人格鲁特', g.m, t.p, z.A, b.d, s.h, [a.d], [{ for: t.p, type: d.e, value: '45%' }], null, 2],
	['树人格鲁特', g.m, t.p, z.f, b.d, s.h, [a.d], [{ for: t.p, type: d.e, value: '45%' }], null, 2],
	['树人格鲁特', g.m, t.p, '雪花庆典', b.d, s.h, [a.d], [{ for: t.p, type: d.e, value: '45%' }], null, 2],
	['死亡战士', g.m, t.p, z.R, b.a, s.h, [a.m, a.q], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['死亡战士', g.m, t.p, z.a, b.a, s.h, [a.m, a.q], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['毒液特工', g.m, t.p, z.c, b.a, s.h, [a.t, a.f, a.q], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['毒液特工', g.m, t.p, '反毒液特工', b.a, s.h, [a.t, a.f, a.q], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['沃斯塔格', g.m, t.p, z.a, b.d, s.h, [a.p], [{ for: q.a, type: d.d, value: '30%' }], null, 2],
	['狼人', g.m, t.p, '咆哮突击队', b.a, s.h, [a.d, a.q], null, [{ for: q.a, type: d.r, value: '30%' }], 2],
	['猩猩人', g.m, t.p, z.a, b.a, s.h, [a.a, a.g, a.n], null, null, 2],
	['角斗士', g.m, t.p, z.a, b.d, s.h, [a.e, a.a, a.f], [{ for: q.a, type: d.a, value: '30%' }], null, 2],
	['野兽', g.m, t.p, z.b, b.b, s.h, [a.a, a.g], [{ for: q.a, type: d.c, value: '45%' }], [{ for: q.a, type: d.E, value: '10%' }, { for: q.a, type: d.h, value: '8%' }, { for: q.a, type: d.M, value: '15%' }], 2],
	['野兽', g.m, t.p, z.F, b.b, s.f, [a.a, a.g], [{ for: q.a, type: d.c, value: '50%' }], [{ for: q.a, type: d.E, value: '10%' }, { for: q.a, type: d.h, value: '8%' }, { for: q.a, type: d.M, value: '15%' }], 2],
	['野兽', g.m, t.p, '非凡X战警', b.b, s.h, [a.a, a.g], [{ for: q.a, type: d.c, value: '50%' }], [{ for: q.a, type: d.E, value: '10%' }, { for: q.a, type: d.h, value: '8%' }, { for: q.a, type: d.M, value: '15%' }], 2],
	['钢力士', g.m, t.p, z.a, b.b, s.h, [a.a, a.f], null, [{ for: q.a, type: d.N, value: '60%' }, { for: q.a, type: d.H, value: '50%' }], 2],
	['钢力士', g.m, t.p, z.C, b.b, s.h, [a.a, a.f], null, [{ for: q.a, type: d.N, value: '60%' }, { for: q.a, type: d.H, value: '50%' }], 2],
	['钢力士', g.m, t.p, z.D, b.b, s.h, [a.a, a.f, a.v], null, [{ for: q.a, type: d.N, value: '60%' }, { for: q.a, type: d.H, value: '50%' }, { for: q.a, type: d.F, value: '50%' }], 2],
	['霍根', g.m, t.p, z.a, b.d, s.h, [a.a], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['弦月神女', g.f, t.p, z.a, b.a, s.h, [a.f, a.p, a.a], [{ for: t.p, type: d.c, value: '60%' }], [{ for: q.b, type: d.a, value: '15%' }, { for: q.b, type: d.d, value: '15%' }], 3],
	['弦月神女', g.f, t.p, '生活方式系列1', b.a, s.h, [a.f, a.p, a.a], [{ for: t.p, type: d.c, value: '60%' }], [{ for: q.b, type: d.a, value: '15%' }, { for: q.b, type: d.d, value: '15%' }], 3],
	['希芙', g.f, t.p, z.R, b.d, s.h, [a.g], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['希芙', g.f, t.p, z.a, b.d, s.h, [a.g], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['杰西卡·琼斯', g.f, t.p, z.a, b.a, s.h, [a.a, a.p, a.I], null, null, 4],
	['杰西卡·琼斯', g.f, t.p, '珍宝女', b.a, s.h, [a.a, a.p, a.I], null, [{ for: a.I, type: d.a, value: '50%' }, { for: a.I, type: d.Q, value: '100%' }], 4],
	['瓦尔基里', g.f, t.p, z.B, b.d, s.h, [a.a], [{ for: q.a, type: d.n, value: '11%' }], [{ for: q.a, type: d.G, value: '45%' }, { for: q.a, type: d.H, value: '15%' }], 4],
	['瓦尔基里', g.f, t.p, '无畏捍卫者', b.d, s.h, [a.a], [{ for: q.a, type: d.n, value: '11%' }], [{ for: q.a, type: d.G, value: '50%' }, { for: q.a, type: d.H, value: '25%' }, { for: q.a, type: d.j, value: '30%' }], 4],
	['女浩克', g.f, t.p, z.r, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.x, value: '48%' }], null, 2],
	['女浩克', g.f, t.p, '全新', b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.x, value: '55%' }], null, 2],
	['女浩克', g.f, t.p, '神奇四侠', b.a, s.h, [a.F, a.p, a.A], [{ for: q.a, type: d.x, value: '60%' }], null, 2],
	['女浩克', g.f, t.p, z.d, b.a, s.h, [a.F, a.p], [{ for: q.a, type: d.x, value: '65%' }], null, 2],
	['惊奇女士（卡玛拉·克汗）', g.f, t.p, z.c, b.c, s.h, [a.a, a.d], [{ for: q.a, type: d.e, value: '45%' }], null, 2],
	['惊奇女士（卡玛拉·克汗）', g.f, t.p, '卡拉奇服装', b.c, s.h, [a.a, a.d], [{ for: q.a, type: d.e, value: '45%' }], null, 2],
	['惊奇女士（卡玛拉·克汗）', g.f, t.p, '异人族：阿提兰崛起', b.c, s.h, [a.a, a.d], [{ for: q.a, type: d.e, value: '45%' }], null, 2],
	['白虎', g.f, t.p, '新复仇者', b.a, s.h, [a.g], null, null, 2],
	['红色女浩克', g.f, t.p, z.a, b.a, s.h, [a.F, a.p, a.i], [{ for: q.a, type: d.l, value: '65%' }, { for: q.a, type: d.g, value: '25%' }], [{ for: q.a, type: d.g, value: '30%' }, { for: q.a, type: d.M, value: '10%' }], 2],
	['艾美利加·查维兹', g.f, t.p, '终极战队', b.a, s.h, [a.a, a.e], [{ for: q.a, type: d.a, value: '26%' }, { for: q.a, type: d.n, value: '6%' }], null, 2],
	['克莱图斯·卡萨伊', g.m, t.p, z.c, b.a, s.f, [a.r, a.d, a.t], [{ for: q.a, type: d.h, value: '6%' }, { for: q.a, type: d.r, value: '18%' }], null, 3],
	['克莱图斯·卡萨伊', g.m, t.p, '绝对屠杀', b.a, s.f, [a.r, a.d, a.t], [{ for: q.a, type: d.h, value: '6%' }, { for: q.a, type: d.r, value: '18%' }], null, 3],
	['天启', g.m, t.p, z.F, b.b, s.f, [a.e, a.r, a.p], [{ for: q.a, type: d.a, value: '18%' }, { for: q.a, type: d.d, value: '18%' }, { for: q.a, type: d.t, value: '6%' }], null, 3],
	['天启', g.m, t.p, '弥赛亚情结', b.b, s.f, [a.e, a.r, a.p], [{ for: q.a, type: d.a, value: '18%' }, { for: q.a, type: d.d, value: '18%' }, { for: q.a, type: d.t, value: '6%' }], null, 3],
	['毒液', g.m, t.p, z.b, b.a, s.f, [a.d, a.t], [{ for: q.a, type: d.i, value: '24%' }], null, 3],
	['毒液', g.m, t.p, z.u, b.a, s.f, [a.d, a.t], [{ for: q.a, type: d.i, value: '24%' }], null, 3],
	['毒液', g.m, t.p, '反毒液', b.a, s.h, [a.d, a.t], [{ for: q.a, type: d.i, value: '24%' }], null, 3],
	['毒液', g.m, t.p, '诸界之战', b.a, s.h, [a.d, a.t], [{ for: q.a, type: d.i, value: '24%' }], null, 3],
	['章鱼博士', g.m, t.p, z.b, b.a, s.f, [a.m, a.p, a.B], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['章鱼博士', g.m, t.p, '超级蜘蛛侠', b.a, s.h, [a.m, a.x, a.g], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['章鱼博士', g.m, t.f, '究极章鱼', b.a, s.f, [a.m, a.B, a.g], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['红卫士', g.m, t.p, z.a, b.a, s.f, [a.a, a.g], [{ for: s.f, type: d.g, value: '35%' }], null, 4],
	['红卫士', g.m, t.p, z.J, b.a, s.h, [a.a, a.g], [{ for: s.h, type: d.g, value: '35%' }], null, 4],
	['莫比亚斯', g.m, t.p, z.a, b.a, s.f, [a.a, a.g], [{ for: q.a, type: d.g, value: '30%' }], null, 4],
	['靶眼', g.m, t.p, z.a, b.a, s.f, [a.n, a.r], [{ for: q.a, type: d.j, value: '50%' }], null, 4],
	['靶眼', g.m, t.p, z.o, b.a, s.f, [a.n, a.r], [{ for: q.a, type: d.j, value: '50%' }], null, 4],
	['靶眼', g.m, t.f, z.T, b.a, s.f, [a.n, a.G], [{ for: q.a, type: d.j, value: '50%' }], null, 4],
	['交叉骨', g.m, t.p, z.k, b.a, s.f, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['交叉骨', g.m, t.p, z.a, b.a, s.f, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['交叉骨', g.m, t.p, '秘密帝国', b.a, s.f, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['克尔芒戈', g.m, t.p, z.b, b.a, s.f, [a.a, a.o], [{ for: q.a, type: d.e, value: '50%' }], null, 2],
	['克尔芒戈', g.m, t.p, z.L, b.a, s.f, [a.a, a.o], [{ for: q.a, type: d.e, value: '50%' }], null, 2],
	['剑齿虎', g.m, t.p, '变种人兄弟会', b.b, s.f, [a.r, a.g], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['剑齿虎', g.m, t.p, z.FG, b.b, s.f, [a.r, a.g], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['吸收人', g.m, t.p, z.a, b.a, s.f, [a.a], [{ for: q.a, type: d.e, value: '45%' }], null, 2],
	['尤里克', g.m, t.p, z.a, b.d, s.f, [a.a, a.p], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['恶型怪', g.m, t.p, z.a, b.a, s.f, [a.F, a.p], [{ for: t.p, type: d.a, value: '60%' }], [{ for: a.F, type: d.K, value: '20%' }, { for: a.F, type: d.w, value: '45%' }, { for: a.F, type: d.G, value: '45%' }], 2],
	['戴肯', g.m, t.p, z.a, b.b, s.f, [a.n, a.d], [{ for: q.a, type: d.i, value: '30%' }], null, 2],
	['斯科尔奇', g.m, t.p, z.B, b.d, s.f, [a.a, a.p], [{ for: q.a, type: d.h, value: '9%' }, { for: q.a, type: d.s, value: '9%' }], null, 2],
	['模仿大师', g.m, t.p, z.a, b.a, s.f, [a.n, a.r], [{ for: q.a, type: d.n, value: '9%' }], [{ for: a.n, type: d.h, value: '20%' }, { for: a.n, type: d.j, value: '20%' }, { for: a.n, type: d.I, value: '25%' }, { for: a.n, type: d.J, value: '20%' }], 2],
	['模仿大师', g.m, t.p, z.J, b.a, s.f, [a.n, a.r], [{ for: q.a, type: d.n, value: '9%' }], [{ for: a.n, type: d.h, value: '20%' }, { for: a.n, type: d.j, value: '20%' }, { for: a.n, type: d.I, value: '25%' }, { for: a.n, type: d.J, value: '20%' }, { for: q.a, type: d.w, value: '40%' }, { for: q.a, type: d.G, value: '40%' }], 2],
	['沙魔', g.m, t.p, z.b, b.a, s.f, [a.p, a.B], [{ for: q.a, type: d.d, value: '24%' }], null, 2],
	['熔浆元素', g.m, t.p, z.P, b.a, s.f, [a.r, a.p, a.i], [{ for: q.a, type: d.d, value: '45%' }], null, 2],
	['犀牛人', g.m, t.p, z.a, z.b, s.f, [a.a, a.p], [{ for: q.a, type: d.u, value: '20%' }], null, 2],
	['红坦克', g.m, t.p, '变种人兄弟会', b.b, s.f, [a.a, a.p, a.r], [{ for: q.a, type: d.d, value: '50%' }], null, 2],
	['红浩克', g.m, t.p, z.a, b.a, s.f, [a.i, a.F], [{ for: q.a, type: d.l, value: '60%' }, { for: q.a, type: d.S, value: '100%' }], null, 2],
	['红浩克', g.m, t.p, z.m, b.a, s.h, [a.i, a.F], [{ for: q.a, type: d.l, value: '60%' }, { for: q.a, type: d.S, value: '100%' }], null, 2],
	['红浩克', g.m, t.p, '复仇共生体', b.a, s.h, [a.i, a.F, a.t], [{ for: q.a, type: d.l, value: '70%' }, { for: q.a, type: d.S, value: '100%' }], null, 2],
	['蜥蜴', g.m, t.p, z.b, b.a, s.f, [a.d, a.B], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['金并', g.m, t.p, z.a, b.a, s.f, [a.a, a.o], [{ for: q.a, type: d.g, value: '30%' }], null, 2],
	['金并', g.m, t.p, z.w, b.a, s.f, [a.a, a.o, a.m], [{ for: q.a, type: d.g, value: '30%' }], null, 2],
	['尖叫', g.f, t.p, z.a, b.a, s.f, [a.a, a.r, a.t], [{ for: q.a, type: d.h, value: '12%' }], null, 2],
	['星云', g.f, t.p, z.z, b.d, s.f, [a.k, a.n], null, null, 2],
	['星云', g.f, t.p, z.b, b.d, s.f, [a.k, a.n], null, null, 2],
	['星云', g.f, t.p, z.g, b.d, s.f, [a.k, a.n], null, null, 2],
	['星云', g.f, t.p, z.h, b.d, s.f, [a.k, a.n], null, null, 2],
	['泰坦尼亚', g.f, t.p, z.a, b.a, s.f, [a.a], [{ for: t.p, type: d.c, value: '50%' }], null, 2],
	['米·勒娃', g.f, t.p, z.a, b.d, s.f, [a.a, a.g, a.r], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['米·勒娃', g.f, t.p, z.M, b.d, s.f, [a.a, a.g, a.r], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['X教授', g.m, t.e, z.a, b.b, s.h, [a.f, a.c, a.s], [{ for: b.b, type: d.a, value: '20%' }, { for: b.b, type: d.z, value: '50%' }], null, 3],
	['X教授', g.m, t.e, z.b, b.b, s.h, [a.f, a.c, a.s], [{ for: b.b, type: d.a, value: '20%' }, { for: b.b, type: d.z, value: '50%' }], null, 3],
	['钢铁侠', g.m, t.e, z.b, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.e, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.p, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.k, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.f, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.g, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.h, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, z.l, b.a, s.h, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['钢铁侠', g.m, t.e, '究极钢铁侠', b.a, s.f, [a.m, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 3],
	['幻视', g.m, t.e, z.a, b.e, s.h, [a.e, a.m, a.p], null, null, 3],
	['幻视', g.m, t.a, z.e, b.e, s.h, [a.e, a.m, a.p], null, null, 3],
	['幻视', g.m, t.e, z.FG, b.e, s.h, [a.e, a.m, a.p], null, null, 3],
	['幻视', g.m, t.a, z.S, b.e, s.h, [a.e, a.m, a.p], [{ for: q.a, type: d.a, value: '20%' }, { for: '猩红女巫', type: d.a, value: '50%' }], null, 3],
	['霹雳火', g.m, t.e, z.a, b.a, s.h, [a.i, a.e, a.A], [{ for: q.a, type: d.l, value: '25%' }], null, 4],
	['霹雳火', g.m, t.e, z.E, b.a, s.h, [a.i, a.e, a.A], [{ for: q.a, type: d.l, value: '25%' }], null, 4],
	['霹雳火', g.m, t.e, z.b, b.a, s.h, [a.i, a.e, a.A], [{ for: q.a, type: d.A, value: '50%' }], null, 4],
	['奇异博士', g.m, t.e, z.c, b.a, s.h, [a.l, a.e], [{ for: q.a, type: d.b, value: '30%' }, { for: q.a, type: d.j, value: '20%' }], null, 3],
	['奇异博士', g.m, t.e, z.Q, b.a, s.h, [a.l, a.e], [{ for: q.a, type: d.b, value: '30%' }, { for: q.a, type: d.j, value: '20%' }], null, 3],
	['奇异博士', g.m, t.e, z.f, b.a, s.h, [a.l, a.e], [{ for: q.a, type: d.b, value: '30%' }, { for: q.a, type: d.j, value: '20%' }], null, 3],
	['奇异博士', g.m, t.e, '太空衣', b.a, s.h, [a.l, a.e], [{ for: q.a, type: d.b, value: '30%' }, { for: q.a, type: d.j, value: '20%' }], null, 3],
	['星爵', g.m, t.e, z.z, b.d, s.h, [a.n, a.f], [{ for: t.e, type: d.b, value: '45%' }], null, 3],
	['星爵', g.m, t.e, '星际盔甲', b.d, s.h, [a.n, a.f], [{ for: t.e, type: d.b, value: '45%' }], null, 3],
	['星爵', g.m, t.e, z.A, b.d, s.h, [a.n, a.f], [{ for: t.e, type: d.b, value: '50%' }], null, 3],
	['星爵', g.m, t.e, z.f, b.d, s.h, [a.n, a.f], [{ for: t.e, type: d.b, value: '50%' }], null, 3],
	['星爵', g.m, t.e, '搁浅', b.d, s.h, [a.n, a.f], [{ for: t.e, type: d.b, value: '55%' }], null, 3],
	['电索', g.m, t.e, z.a, b.b, s.h, [a.n, a.f], [{ for: q.a, type: d.j, value: '50%' }], null, 3],
	['电索', g.m, t.e, 'X特攻队', b.b, s.h, [a.n, a.f], [{ for: q.a, type: d.j, value: '50%' }], null, 3],
	['电索', g.m, t.e, '电索&死侍', b.b, s.h, [a.n, a.f], [{ for: q.a, type: d.j, value: '50%' }], null, 3],
	['电索', g.m, t.e, '夏日时光', b.b, s.h, [a.n, a.f], [{ for: q.a, type: d.j, value: '50%' }], null, 3],
	['电索', g.m, t.e, 'X之剑', b.b, s.h, [a.n, a.f], [{ for: q.a, type: d.j, value: '50%' }], null, 3],
	['镭射眼', g.m, t.e, z.b, b.b, s.h, [a.u, a.o], [{ for: q.a, type: d.a, value: '25%' }, { for: q.a, type: d.d, value: '25%' }], [{ for: q.a, type: d.b, value: '10%' }], 3],
	['镭射眼', g.m, t.e, z.F, b.b, s.f, [a.u, a.o], [{ for: q.a, type: d.a, value: '25%' }, { for: q.a, type: d.d, value: '25%' }], [{ for: q.a, type: d.b, value: '15%' }], 3],
	['镭射眼', g.m, t.e, z.m, b.b, s.h, [a.u, a.o], [{ for: q.a, type: d.a, value: '35%' }, { for: q.a, type: d.d, value: '25%' }], [{ for: q.a, type: d.b, value: '15%' }], 3],
	['镭射眼', g.m, t.e, z.D, b.b, s.f, [a.u, a.o, a.v], [{ for: q.a, type: d.a, value: '35%' }, { for: q.a, type: d.d, value: '25%' }], [{ for: q.a, type: d.b, value: '30%' }], 3],
	['牌皇', g.m, t.e, z.a, b.b, s.h, [a.g, a.c], [{ for: q.a, type: d.j, value: '50%' }], null, 4],
	['牌皇', g.m, t.e, '圣剑', b.b, s.h, [a.g, a.c], [{ for: q.a, type: d.j, value: '50%' }], null, 4],
	['冰人', g.m, t.e, z.a, b.b, s.h, [a.j, a.y], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['冰人', g.m, t.e, 'X战警蓝队', b.b, s.h, [a.j, a.y], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['古一', g.m, t.e, z.a, b.a, s.h, [a.l, a.f], [{ for: t.e, type: d.b, value: '45%' }], [{ for: q.a, type: d.j, value: '25%' }, { for: q.a, type: d.D, value: '25%' }], 2],
	['古一', g.f, t.e, z.Q, b.a, s.h, [a.l, a.f], [{ for: t.e, type: d.b, value: '45%' }], [{ for: q.a, type: d.j, value: '25%' }, { for: q.a, type: d.D, value: '25%' }], 2],
	['宇宙魔士亚当', g.m, t.e, z.a, b.e, s.h, [a.l, a.z], [{ for: q.a, type: d.f, value: '60%' }], null, 2],
	['巫术', g.m, t.e, '新复仇者', b.a, s.h, [a.e, a.u], [{ for: q.a, type: d.a, value: '24%' }], [{ for: q.a, type: d.j, value: '20%' }], 2],
	['战争机器', g.m, t.e, z.a, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, '钢铁爱国者', b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, '复仇者联盟：主导权', b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, z.k, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, z.f, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, z.g, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['战争机器', g.m, t.e, z.h, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.c, value: '30%' }], null, 2],
	['林肯坎贝尔', g.m, t.e, z.R, b.c, s.h, [a.k], [{ for: q.a, type: d.m, value: '60%' }], null, 2],
	['欧米伽小子', g.m, t.e, z.a, b.b, s.h, [a.v, a.u], [{ for: q.a, type: d.o, value: '40%' }], null, 2],
	['毕晓普', g.m, t.e, '解散', b.b, s.h, [a.u], [{ for: q.a, type: d.f, value: '45%' }, { for: q.a, type: d.b, value: '24%' }], null, 2],
	['火箭浣熊', g.m, t.e, z.z, b.d, s.h, [a.n], null, null, 2],
	['火箭浣熊', g.m, t.e, z.c, b.d, s.h, [a.n], null, null, 2],
	['火箭浣熊', g.m, t.e, z.A, b.d, s.h, [a.n], null, null, 2],
	['火箭浣熊', g.m, t.e, z.f, b.d, s.h, [a.n], null, null, 2],
	['火箭浣熊', g.m, t.e, z.g, b.d, s.h, [a.n], null, null, 2],
	['火箭浣熊', g.m, t.e, z.h, b.d, s.h, [a.n], null, null, 2],
	['烈火', g.m, t.e, z.c, b.c, s.h, [a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 2],
	['烈火', g.m, t.e, z.a, b.c, s.h, [a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 2],
	['菲尔·科尔森', g.m, t.e, z.R, b.a, s.h, [a.o, a.q], null, [{ for: s.h, type: d.h, value: '20%' }, { for: s.h, type: d.G, value: '45%' }, { for: s.h, type: d.H, value: '15%' }], 2],
	['菲尔·科尔森', g.m, t.e, 'A.O.S. 第三季', b.a, s.h, [a.o, a.q], null, [{ for: s.h, type: d.h, value: '20%' }, { for: s.h, type: d.G, value: '45%' }, { for: s.h, type: d.H, value: '15%' }, { for: s.h, type: d.d, value: '10%' }], 2],
	['猩红女巫', g.f, t.e, z.b, b.f, s.h, [a.w, a.e], [{ for: q.a, type: d.b, value: '45%' }], null, 3],
	['猩红女巫', g.f, t.e, z.f, b.f, s.h, [a.w, a.e], [{ for: q.a, type: d.b, value: '45%' }], null, 3],
	['猩红女巫', g.f, t.e, z.FG, b.f, s.h, [a.w, a.e], [{ for: q.a, type: d.b, value: '45%' }], null, 3],
	['猩红女巫', g.f, t.e, z.c, b.f, s.h, [a.w, a.e], [{ for: q.a, type: d.b, value: '45%' }], null, 3],
	['猩红女巫', g.f, t.a, z.S, b.f, s.h, [a.w, a.e], [{ for: q.a, type: d.b, value: '45%' }], null, 3],
	['隐形女侠', g.f, t.e, z.a, b.a, s.h, [a.u, a.A], [{ for: q.a, type: d.z, value: '50%' }], null, 4],
	['隐形女侠', g.f, t.e, z.E, b.a, s.h, [a.u, a.A], [{ for: q.a, type: d.z, value: '50%' }], null, 4],
	['隐形女侠', g.f, t.e, z.b, b.a, s.h, [a.u, a.A], [{ for: q.a, type: d.z, value: '50%' }], null, 4],
	['暴风女', g.f, t.e, z.a, b.b, s.h, [a.k, a.o], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.m, value: '12%' }, { for: q.a, type: d.R, value: '50%概率' }], 3],
	['暴风女', g.f, t.e, 'X战警红队', b.b, s.h, [a.k, a.o], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.m, value: '12%' }, { for: q.a, type: d.R, value: '50%概率' }], 3],
	['暴风女', g.f, t.e, '异人族 vs X战警', b.b, s.h, [a.k, a.o], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.D, value: '35%' }], 3],
	['琴·格蕾', g.f, t.e, '凤凰', b.b, s.h, [a.c, a.s, a.v], null, null, 3],
	['琴·格蕾', g.f, t.e, 'X战警红队', b.b, s.h, [a.c, a.s, a.v], null, null, 3],
	['琴·格蕾', g.f, t.a, '惊奇少女', b.b, s.h, [a.c, a.s, a.v], null, null, 3],
	['美国队长（莎伦·罗杰斯）', g.f, t.e, '美国队长75周年纪念', b.a, s.h, [a.f, a.u], null, null, 3],
	['美国队长（莎伦·罗杰斯）', g.f, t.e, '星光装甲', b.a, s.h, [a.f, a.u], null, null, 3],
	['美国队长（莎伦·罗杰斯）', g.f, t.e, '暗星装甲', b.a, s.h, [a.f, a.u], null, null, 3],
	['美国队长（莎伦·罗杰斯）', g.f, t.e, '星夜装甲', b.a, s.h, [a.f, a.u], null, null, 3],
	['蜘蛛女', g.f, t.e, z.a, b.a, s.h, [a.x, a.f, a.g], null, null, 4],
	['青龙', g.f, t.e, z.a, b.a, s.h, [a.D, a.f, a.k], [{ for: a.D, type: d.a, value: '65%' }], null, 4],
	['咒术武器', g.f, t.e, z.O, b.b, s.h, [a.g, a.d, a.w], [{ for: q.a, type: d.n, value: '6%' }, { for: q.a, type: d.i, value: '24%' }], null, 2],
	['救援', g.f, t.e, z.g, b.a, s.h, [a.m, a.f], null, null, 2],
	['月亮女孩', g.f, t.e, z.m, b.c, s.h, [a.n, a.f], [{ for: q.a, type: d.a, value: '36%' }], null, 2],
	['月亮女孩', g.f, t.e, '怪兽出笼！（MFF变体）', b.c, s.h, [a.n, a.f], [{ for: q.a, type: d.a, value: '36%' }], null, 2],
	['格林妹妹', g.f, t.e, z.r, b.a, s.h, [a.l], null, null, 2],
	['格林妹妹', g.f, t.e, z.c, b.a, s.h, [a.l], null, null, 2],
	['歌姬', g.f, t.e, '新复仇者', b.a, s.h, [a.e, a.q], [{ for: q.a, type: d.t, value: '9%' }], null, 2],
	['水晶', g.f, t.e, z.c, b.c, s.h, [a.o, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['水晶', g.f, t.e, '皇家礼服', b.c, s.h, [a.o, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['水晶', g.f, t.e, '神奇四侠', b.c, s.h, [a.o, a.u, a.A], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['灵蝶', g.f, t.e, z.C, b.b, s.h, [a.g, a.c], [{ for: q.a, type: d.z, value: '50%' }], null, 2],
	['灵蝶', g.f, t.e, '解散', b.b, s.h, [a.g, a.c], [{ for: q.a, type: d.z, value: '50%' }], null, 2],
	['炫音', g.f, t.e, z.a, b.b, s.h, [a.u], [{ for: q.a, type: d.h, value: '6%' }], [{ for: b.b, type: d.j, value: '70%' }, { for: b.b, type: d.y, value: '65%' }], 2],
	['瑞秋·萨默斯', g.f, t.e, z.a, b.b, s.h, [a.v, a.e], [{ for: q.a, type: d.z, value: '40%' }], null, 2],
	['瑟西', g.f, t.e, z.a, b.d, s.h, [a.H, a.f, a.l], [{ for: q.a, type: d.t, value: '6%' }], [{ for: a.H, type: d.a, value: '30%' }], 2],
	['白光花火', g.f, t.e, z.b, b.b, s.h, [a.u], [{ for: q.a, type: d.z, value: '50%' }], null, 2],
	['艾玛·弗斯特', g.f, t.e, z.a, b.b, s.h, [a.s, a.p], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['艾玛·弗斯特', g.f, t.e, z.m, b.b, s.h, [a.s, a.p], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['艾玛·弗斯特', g.f, t.e, z.D, b.b, s.f, [a.s, a.p, a.v], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['螳螂', g.f, t.e, z.A, b.d, s.h, [a.c, a.d], [{ for: q.a, type: d.i, value: '24%' }], [{ for: q.a, type: d.r, value: '20%' }, { for: q.a, type: d.u, value: '15%' }], 2],
	['钢铁之心', g.f, t.e, z.m, b.a, s.h, [a.m, a.f], [{ for: q.a, type: d.b, value: '45%' }], null, 2],
	['魔剑客', g.f, t.e, z.a, b.b, s.h, [a.l, a.s], [{ for: q.a, type: d.h, value: '13%' }], null, 2],
	['魔剑客', g.f, t.e, z.D, b.b, s.f, [a.l, a.s, a.v], [{ for: q.a, type: d.h, value: '13%' }], null, 2],
	['黄蜂女', g.f, t.e, z.a, b.a, s.h, [a.e], [{ for: q.a, type: d.a, value: '18%' }, { for: q.a, type: d.d, value: '18%' }, { for: q.a, type: d.t, value: '6%' }], null, 2],
	['黄蜂女', g.f, t.e, z.c, b.a, s.h, [a.e], [{ for: q.a, type: d.a, value: '18%' }, { for: q.a, type: d.d, value: '18%' }, { for: q.a, type: d.t, value: '6%' }], null, 2],
	['黄蜂女', g.f, t.e, z.I, b.a, s.h, [a.e], [{ for: q.a, type: d.a, value: '23%' }, { for: q.a, type: d.d, value: '18%' }, { for: q.a, type: d.t, value: '6%' }], null, 2],
	['黄蜂女（纳迪娅·凡·戴思）', g.f, t.e, z.a, b.a, s.h, [a.q, a.e], [{ for: q.a, type: d.n, value: '11%' },], null, 2],
	['黑后', g.f, t.e, z.a, b.b, s.h, [a.g, a.e, a.u], [{ for: q.a, type: d.i, value: '30%' }], null, 2],
	['黛西·约翰逊', g.f, t.e, z.R, b.c, s.h, [a.s, a.q], null, null, 2],
	['震波女(黛西·约翰逊)', g.f, t.e, z.a, b.c, s.h, [a.o, a.q], null, null, 2],
	['黛西·约翰逊', g.f, t.e, '神盾局特工（震波女）', b.c, s.h, [a.s, a.q], null, null, 2],
	['墨菲斯托', g.m, t.e, z.a, b.f, s.f, [a.J, a.l, a.r], null, null, 3],
	['万磁王', g.m, t.e, z.b, b.b, s.f, [a.u, a.s], [{ for: b.b, type: d.a, value: '45%' }], null, 3],
	['万磁王', g.m, t.e, z.m, b.b, s.f, [a.u, a.s], [{ for: b.b, type: d.a, value: '45%' }], null, 3],
	['万磁王', g.m, t.e, 'X皇室', b.b, s.f, [a.u, a.s], [{ for: b.b, type: d.a, value: '45%' }], null, 3],
	['红骷髅', g.m, t.e, z.i, b.a, s.f, [a.r, a.o], [{ for: q.a, type: d.d, value: '24%' }], null, 4],
	['红骷髅', g.m, t.f, z.v, b.a, s.f, [a.r, a.o], [{ for: q.a, type: d.d, value: '24%' }], null, 4],
	['红骷髅', g.m, t.e, '九头蛇盔甲', b.a, s.f, [a.r, a.o, a.E], [{ for: q.a, type: d.d, value: '24%' }], null, 4],
	['卡西利亚斯', g.m, t.e, z.Q, b.a, s.f, [a.l, a.g], [{ for: q.a, type: d.e, value: '45%' }], null, 2],
	['尤利西斯克劳', g.m, t.e, z.L, b.a, s.f, [a.n], [{ for: q.a, type: d.h, value: '13%' }], [{ for: q.a, type: d.r, value: '30%' }], 2],
	['斯特拉夫', g.m, t.e, z.a, b.b, s.f, [a.r, a.u], null, null, 2],
	['猛水元素', g.m, t.e, z.P, b.a, s.f, [a.r], [{ for: q.a, type: d.e, value: '20%' }, { for: q.a, type: d.U, value: '100%' }, { for: q.a, type: d.V, value: '100%' }], null, 2],
	['罪恶先生', g.m, t.e, z.a, b.b, s.f, [a.r, a.u, a.d], [{ for: q.a, type: d.z, value: '50%' }], null, 2],
	['致幻客', g.m, t.e, z.b, b.a, s.f, [a.c, a.B], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['致幻客', g.m, t.e, z.P, b.a, s.f, [a.c, a.B], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['莫度男爵', g.m, t.e, z.b, b.a, s.f, [a.l, a.r], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['莫度男爵', g.m, t.f, z.Q, b.a, s.h, [a.g, a.b], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['鞭挞', g.m, t.e, z.R, b.c, s.f, [a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['鞭挞', g.m, t.e, z.a, b.c, s.f, [a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['鞭索', g.m, t.e, '电影：钢铁侠2', b.a, s.f, [a.k, a.m], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['马西姆斯', g.m, t.e, '王者之战', b.c, s.f, [a.s, a.r], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['魔雷基', g.m, t.e, '雷神索尔：黑暗世界', b.d, s.f, [a.r], null, null, 2],
	['魔雷基', g.m, t.e, z.c, b.d, s.f, [a.r], null, null, 2],
	['黄杉侠', g.m, t.e, z.H, b.a, s.f, [a.r, a.m], null, null, 2],
	['默多克', g.m, t.e, z.b, b.a, s.f, [a.c, a.m, a.r], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['默多克', g.m, t.e, '史派多', b.a, s.f, [a.c, a.m, a.r], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['默多克', g.m, t.e, '凯普多', b.a, s.f, [a.c, a.m, a.r], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['月光石', g.f, t.e, z.T, b.a, s.f, [a.G, a.u], [{ for: q.a, type: d.n, value: '6%' }], null, 4],
	['魅惑魔女', g.f, t.e, z.a, b.d, s.f, [a.l, a.c], [{ for: q.a, type: d.v, value: '25%' }], null, 2],
	['魅惑魔女', g.f, t.e, '夏日时光', b.d, s.f, [a.l, a.c], [{ for: q.a, type: d.v, value: '40%' }], [{ for: q.a, type: d.o, value: '30%' }], 2],
	['冬兵', g.m, t.f, z.j, b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['冬兵', g.m, t.f, z.k, b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['冬兵', g.m, t.f, '美国队长', b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['冬兵', g.m, t.f, z.f, b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 3],
	['夜魔侠', g.m, t.f, z.a, b.a, s.h, [a.b, a.I, a.f], null, null, 3],
	['夜魔侠', g.m, t.f, '厨房恶魔', b.a, s.h, [a.b, a.I, a.f], null, null, 3],
	['夜魔侠', g.m, t.f, z.c, b.a, s.h, [a.b, a.I, a.f], null, null, 3],
	['夜魔侠', g.m, t.f, '失去人心', b.a, s.h, [a.b, a.I, a.f], null, null, 3],
	['快银', g.m, t.f, z.b, b.f, s.h, [a.e, a.g], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.n, value: '6%' }], null, 3],
	['快银', g.m, t.f, '漫威传承', b.f, s.h, [a.e, a.g], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.n, value: '6%' }], null, 3],
	['快银', g.m, t.f, z.FG, b.f, s.h, [a.e, a.g], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.n, value: '6%' }], null, 3],
	['死侍', g.m, t.f, z.a, b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['死侍', g.m, t.f, z.C, b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['死侍', g.f, t.f, '女死侍', b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['死侍', g.f, t.f, '假日派对', b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['死侍', g.m, t.f, '30周年纪念（黑色版）', b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['死侍', g.m, t.f, '30周年纪念（白色版）', b.b, s.h, [a.d, a.n], [{ for: q.a, type: d.E, value: '6%' }], null, 3],
	['蚁人', g.m, t.f, z.a, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蚁人', g.m, t.f, z.H, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蚁人', g.m, t.f, z.k, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蚁人', g.m, t.f, z.I, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蚁人', g.m, t.f, z.g, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蚁人', g.m, t.f, z.h, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.a, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.x, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.c, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.k, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, '蜘蛛侠：英雄归来DIY制服', b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.f, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, z.P, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['蜘蛛侠', g.m, t.f, '蜘蛛侠：英雄远征（隐身衣）', b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 3],
	['凤凰', g.m, t.f, z.a, b.a, s.h, [a.D, a.g, a.i], [{ for: q.a, type: d.t, value: '6%' }], null, 4],
	['夜行者', g.m, t.f, z.a, b.b, s.h, [a.g, a.f], [{ for: q.a, type: d.t, value: '6%' }], null, 4],
	['夜行者', g.m, t.f, z.C, b.b, s.h, [a.g, a.f], [{ for: q.a, type: d.t, value: '6%' }], null, 4],
	['夜行者', g.m, t.f, z.b, b.b, s.h, [a.g, a.f], [{ for: q.a, type: d.t, value: '6%' }], null, 4],
	['勇度', g.m, t.f, z.z, b.d, s.h, [a.o, a.n], [{ for: q.a, type: d.h, value: '7.8%' }], null, 2],
	['勇度', g.m, t.f, z.c, b.d, s.h, [a.o, a.n], [{ for: q.a, type: d.h, value: '7.8%' }], null, 2],
	['勇度', g.m, t.f, z.A, b.d, s.h, [a.o, a.n], [{ for: q.a, type: d.h, value: '7.8%' }], null, 2],
	['卡尔纳克', g.m, t.f, '王者之战', b.c, s.h, [a.b], [{ for: q.a, type: d.t, value: '9%' }], null, 2],
	['卡尔纳克', g.m, t.f, z.c, b.c, s.h, [a.b], [{ for: q.a, type: d.t, value: '9%' }], null, 2],
	['天使', g.m, t.f, z.a, b.b, s.h, [a.e, a.f], null, [{ for: q.a, type: d.E, value: '30%' }], 2],
	['天使', g.m, t.f, z.C, b.b, s.h, [a.e, a.f], null, [{ for: q.a, type: d.E, value: '30%' }], 2],
	['尼克·弗瑞', g.m, t.f, z.a, b.a, s.h, [a.q, a.f, a.n], [{ for: s.h, type: d.a, value: '50%' }], [{ for: s.h, type: d.X, value: '' }, { for: s.h, type: d.d, value: '30%' }, { for: s.h, type: d.G, value: '50%' }], 2],
	['尼克·弗瑞', g.m, t.f, z.M, b.a, s.h, [a.q, a.f, a.n], [{ for: s.h, type: d.a, value: '50%' }], [{ for: s.h, type: d.X, value: '' }, { for: s.h, type: d.d, value: '30%' }, { for: s.h, type: d.G, value: '55%' }, { for: '技能buff', type: d.a, value: '80%' }], 2],
	['怪兽小子', g.m, t.f, '怪兽出笼！（MFF变体）', b.c, s.h, [a.o], [{ for: q.a, type: d.a, value: '20%' }, { for: q.a, type: d.d, value: '20%' }, { for: q.a, type: d.t, value: '10%' }], null, 2],
	['猎鹰', g.m, t.f, z.j, b.a, s.h, [a.e, a.f], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['猎鹰', g.m, t.f, '全新美国队长', b.a, s.h, [a.e, a.f], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['猎鹰', g.m, t.f, z.k, b.a, s.h, [a.e, a.f], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['猎鹰', g.m, t.f, '漫威遗产', b.a, s.h, [a.e, a.f], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['猩红蜘蛛', g.m, t.f, z.a, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.n, value: '6%' }], [{ for: a.x, type: d.w, value: '35%' }, { for: a.x, type: d.G, value: '40%' }, { for: a.x, type: d.I, value: '25%' }, { for: a.x, type: d.J, value: '20%' }], 2],
	['王', g.m, t.f, z.c, b.a, s.h, [a.n], null, null, 2],
	['王', g.m, t.f, z.Q, b.a, s.h, [a.n], null, null, 2],
	['白幽灵', g.m, t.f, z.C, b.b, s.h, [a.g, a.n], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['范达尔', g.m, t.f, z.a, b.d, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 2],
	['蜘蛛侠（迈尔斯·莫拉莱斯）', g.m, t.f, z.c, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['蜘蛛侠（迈尔斯·莫拉莱斯）', g.m, t.f, '平行宇宙', b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['蜘蛛侠（迈尔斯·莫拉莱斯）', g.m, t.f, '绝对屠杀', b.a, s.f, [a.x, a.t, a.r], [{ for: q.a, type: d.i, value: '24%' }, { for: '克莱图斯·卡萨伊', type: d.a, value: '70%' }, { for: '克莱图斯·卡萨伊', type: d.M, value: '20%' }], null, 2],
	['蜘蛛侠2099', g.m, t.f, z.a, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.j, value: '50%' }], null, 2],
	['蜘蛛侠2099', g.m, t.f, z.c, b.a, s.h, [a.x, a.f, a.g], [{ for: q.a, type: d.j, value: '50%' }], null, 2],
	['蜘蛛骑士', g.m, t.f, z.O, b.a, s.h, [a.f, a.n, a.x], [{ for: q.a, type: d.i, value: '24%' }, { for: q.a, type: d.n, value: '6%' }], null, 2],
	['鹰眼', g.m, t.f, z.d, b.a, s.h, [a.n, a.q], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['鹰眼', g.m, t.f, z.e, b.a, s.h, [a.n, a.q], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['鹰眼', g.m, t.f, z.k, b.a, s.h, [a.n, a.q], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['鹰眼', g.m, t.f, z.b, b.a, s.h, [a.n, a.q], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['鹰眼', g.m, t.f, z.g, b.a, s.h, [a.n, a.q], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['黑鹰', g.m, t.f, z.a, b.a, s.h, [a.f, a.e], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['冰月花雪', g.f, t.f, z.a, b.a, s.h, [a.f, a.y], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.P, value: '30%概率' }], null, 3],
	['冰月花雪', g.f, t.f, '仙女座套装', b.a, s.h, [a.f, a.y], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.P, value: '30%概率' }], null, 3],
	['冰月花雪', g.f, t.f, '生活方式系列1', b.a, s.h, [a.f, a.y], [{ for: q.a, type: d.t, value: '6%' }, { for: q.a, type: d.P, value: '30%概率' }], null, 3],
	['小淘气', g.f, t.f, z.b, b.b, s.h, [a.d, a.e], [{ for: q.a, type: d.d, value: '36%' }], null, 3],
	['小淘气', g.f, t.f, z.F, b.b, s.h, [a.d, a.e], [{ for: q.a, type: d.d, value: '36%' }], null, 3],
	['小淘气', g.f, t.f, z.FG, b.b, s.h, [a.d, a.e], [{ for: q.a, type: d.d, value: '36%' }], null, 3],
	['小淘气', g.f, t.f, '圣剑', b.b, s.h, [a.d, a.e], [{ for: q.a, type: d.d, value: '36%' }], null, 3],
	['黑寡妇', g.f, t.f, z.d, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.e, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.p, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.k, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.f, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.g, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.h, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.l, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.J, b.a, s.h, [a.g, a.q], null, null, 3],
	['黑寡妇', g.f, t.f, z.K, b.a, s.h, [a.g, a.q], null, null, 3],
	['X-23', g.f, t.f, z.b, b.b, s.h, [a.g, a.d], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['X-23', g.f, t.f, z.C, b.b, s.h, [a.g, a.d], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['X-23', g.f, t.f, '全新金刚狼', b.b, s.h, [a.g, a.d], [{ for: q.a, type: d.i, value: '24%' }], null, 4],
	['艾尔莎·血石', g.f, t.f, z.a, b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 4],
	['艾尔莎·血石', g.f, t.f, z.u, b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 4],
	['艾尔莎·血石', g.f, t.f, '怪兽出笼！（MFF变体）', b.a, s.h, [a.n], [{ for: q.a, type: d.c, value: '30%' }], null, 4],
	['蛛丝', g.f, t.f, z.c, b.a, s.h, [a.x, a.g], null, null, 4],
	['蛛丝', g.f, t.f, '蛛网套装', b.a, s.h, [a.x, a.g], null, null, 4],
	['蜘蛛格温', g.f, t.f, z.c, b.a, s.h, [a.x, a.f, a.g], null, null, 4],
	['蜘蛛格温', g.f, t.f, '格温多林·斯泰西', b.a, s.h, [a.x, a.f, a.g], null, null, 4],
	['蜘蛛格温', g.f, t.f, '毒液格温', b.a, s.f, [a.x, a.g, a.t], null, null, 4],
	['仿声鸟', g.f, t.f, '英雄时代', b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['芭比·莫斯（仿声鸟）', g.f, t.f, z.R, b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['仿声鸟', g.f, t.f, z.c, b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['凯蒂·普莱德', g.f, t.f, z.a, b.b, s.h, [a.o, a.n], [{ for: b.b, type: d.a, value: '55%' }, { for: b.b, type: d.h, value: '6%' }], null, 2],
	['地狱猫', g.f, t.f, z.c, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '9%' }], null, 2],
	['多米诺', g.f, t.f, z.C, b.b, s.h, [a.g, a.n], [{ for: q.a, type: d.h, value: '8%' }, { for: q.a, type: d.j, value: '45%' }], null, 2],
	['多米诺', g.f, t.f, z.m, b.b, s.h, [a.g, a.n], [{ for: q.a, type: d.h, value: '8%' }, { for: q.a, type: d.j, value: '45%' }], null, 2],
	['幻影刺客', g.f, t.f, z.b, b.a, s.h, [a.n], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['幻影刺客', g.f, t.f, '漫威影剧 夜魔侠', b.a, s.h, [a.n], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['松鼠女', g.f, t.f, '新复仇者', b.a, s.h, [a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['松鼠女', g.f, t.f, z.m, b.a, s.h, [a.g], [{ for: q.a, type: d.n, value: '6%' }], null, 2],
	['格温侍', g.f, t.f, z.c, b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['格温侍', g.f, t.f, '格温侍', b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['格温侍', g.f, t.f, '假日派对', b.a, s.h, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['气旋', g.f, t.f, z.a, b.a, s.h, [a.f, a.e], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['浪', g.f, t.f, z.a, b.a, s.h, [a.b, a.g], [{ for: q.a, type: d.t, value: '6%' }, { for: '纳摩', type: d.a, value: '60%' }], [{ for: s.h, type: d.G, value: '40%' }, { for: s.h, type: d.H, value: '15%' }], 2],
	['白狐', g.f, t.f, z.a, b.a, s.h, [a.g, a.q, a.f], [{ for: q.a, type: d.v, value: '40%' }, { for: q.a, type: d.i, value: '24%' }], [{ for: a.f, type: d.G, value: '60%' }], 2],
	['白狐', g.f, t.f, '生活方式系列1', b.a, s.h, [a.g, a.q, a.f], [{ for: q.a, type: d.v, value: '40%' }, { for: q.a, type: d.i, value: '24%' }], [{ for: a.f, type: d.G, value: '60%' }, { for: a.f, type: d.a, value: '10%' }, { for: a.f, type: d.T, value: '100%' }], 2],
	['白狐', g.f, t.f, '生活方式系列1', b.a, s.h, [a.g, a.q, a.f], [{ for: q.a, type: d.v, value: '40%' }, { for: q.a, type: d.i, value: '24%' }], [{ for: a.f, type: d.G, value: '65%' }, { for: a.f, type: d.H, value: '30%' }, { for: s.h, type: d.a, value: '15%' }, { for: s.h, type: d.K, value: '10%' }, { for: s.h, type: d.j, value: '30%' }], 2],
	['舒莉', g.f, t.f, '漫威遗产', b.a, s.h, [a.b, a.f], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.G, value: '35%' }, { for: q.a, type: d.H, value: '25%' }], 2],
	['舒莉', g.f, t.f, z.L, b.a, s.h, [a.b, a.f], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.G, value: '45%' }, { for: q.a, type: d.H, value: '35%' }], 2],
	['莎伦·卡特', g.f, t.f, z.a, b.a, s.h, [a.q], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['莎伦·卡特', g.f, t.f, z.k, b.a, s.h, [a.q], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['葛摩拉', g.f, t.f, z.z, b.d, s.h, [a.g, a.n], [{ for: t.f, type: d.s, value: '13.5%' }], null, 2],
	['葛摩拉', g.f, t.f, z.c, b.d, s.h, [a.g, a.n], [{ for: t.f, type: d.s, value: '13.5%' }], null, 2],
	['葛摩拉', g.f, t.f, z.A, b.d, s.h, [a.g, a.n], [{ for: t.f, type: d.s, value: '13.5%' }], null, 2],
	['迷雾骑士', g.f, t.f, z.c, b.a, s.h, [a.q, a.n], [{ for: q.a, type: d.q, value: '60%' }], null, 2],
	['鹰眼（凯特·毕晓普）', g.f, t.f, z.m, b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.h, value: '15%' }], null, 2],
	['幽灵', g.m, t.f, z.a, b.a, s.f, [a.n, a.m], [{ for: a.m, type: d.a, value: '50%' }], [{ for: s.f, type: d.b, value: '10%' }], 2],
	['幽灵', g.f, t.f, z.I, b.a, s.f, [a.n, a.m], [{ for: a.m, type: d.a, value: '50%' }], [{ for: s.f, type: d.b, value: '20%' }], 2],
	['泽莫男爵', g.m, t.f, z.a, b.a, s.f, [a.g, a.r], [{ for: s.f, type: d.a, value: '50%' }], null, 2],
	['猎人克莱文', g.m, t.f, z.a, b.a, s.f, [a.n, a.g, a.B], [{ for: q.a, type: d.r, value: '12%' }], null, 2],
	['电王', g.m, t.f, z.a, b.a, s.f, [a.r, a.k, a.B], [{ for: a.B, type: d.a, value: '40%' }, { for: a.B, type: d.d, value: '40%' }, { for: a.B, type: d.t, value: '10%' }], [{ for: q.a, type: d.m, value: '15%' }], 2],
	['秃鹫', g.m, t.f, z.b, b.a, s.f, [a.e, a.g, a.B], [{ for: q.a, type: d.n, value: '6%' }, { for: q.a, type: d.h, value: '9%' }], null, 2],
	['秃鹫', g.m, t.f, '蜘蛛侠：英雄归来', b.a, s.f, [a.e, a.g, a.B], [{ for: q.a, type: d.n, value: '6%' }, { for: q.a, type: d.h, value: '9%' }], null, 2],
	['科拉斯', g.m, t.f, z.M, b.d, s.f, [a.n, a.r], [{ for: q.a, type: d.t, value: '10%' }], null, 2],
	['绿魔', g.m, t.f, z.b, b.a, s.f, [a.h, a.e], [{ for: q.a, type: d.C, value: '50%' }], null, 2],
	['绿魔', g.m, t.f, '终极', b.a, s.f, [a.i, a.e], [{ for: q.a, type: d.A, value: '50%' }], null, 2],
	['绿魔', g.m, t.f, z.T, b.a, s.f, [a.G, a.m, a.u], [{ for: a.G, type: d.a, value: '60%' }], [{ for: a.G, type: d.w, value: '40%' }, { for: a.G, type: d.G, value: '40%' }], 2],
	['蝎子', g.m, t.f, z.a, b.a, s.f, [a.r, a.p, a.h], [{ for: q.a, type: d.d, value: '50%' }], null, 2],
	['魔形女', g.f, t.f, z.a, b.b, s.f, [a.g, a.n], [{ for: q.a, type: d.t, value: '6%' }], [{ for: q.a, type: d.w, value: '45%' }, { for: q.a, type: d.w, value: '40%' }], 4],
	['原罪', g.f, t.f, z.c, b.a, s.f, [a.n, a.r], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['叶莲娜·贝洛娃', g.f, t.f, z.a, b.a, s.f, [a.g, a.q], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['叶莲娜·贝洛娃', g.f, t.f, z.J, b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['叶莲娜·贝洛娃', g.f, t.f, z.K, b.a, s.h, [a.g, a.q], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['蝰蛇', g.f, t.f, z.a, b.a, s.f, [a.h, a.r], [{ for: q.a, type: d.p, value: '40%' }], null, 2],
	['黑猫', g.f, t.f, z.a, b.a, s.f, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['黑猫', g.f, t.f, '服饰', b.a, s.f, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['黑猫', g.f, t.f, z.c, b.a, s.f, [a.g], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['哨兵', g.m, t.a, z.a, b.a, s.h, [a.G, a.f, a.u], null, null, 3],
	['奥丁', g.m, t.a, z.a, b.d, s.h, [a.o, a.u], null, null, 3],
	['奥丁', g.m, t.a, '主神', b.d, s.h, [a.o, a.u], null, null, 3],
	['恶灵骑士', g.m, t.a, z.b, b.a, s.h, [a.f, a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 3],
	['恶灵骑士', g.m, t.a, '70年代古典', b.a, s.h, [a.f, a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 3],
	['恶灵骑士', g.m, t.a, '异人族：阿提兰崛起', b.a, s.h, [a.f, a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 3],
	['恶灵骑士', g.m, t.a, '地狱之王', b.a, s.h, [a.f, a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 3],
	['银河冲浪者', g.m, t.a, z.a, b.d, s.h, [a.C], null, null, 3],
	['银河冲浪者', g.m, t.a, '黑色', b.d, s.h, [a.C], null, null, 3],
	['雷神索尔', g.m, t.a, z.d, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, z.e, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, '失格', b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, z.B, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, z.f, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, z.g, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, z.h, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['雷神索尔', g.m, t.a, '雷霆先锋', b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.B, value: '50%' }], null, 3],
	['黑霹雷', g.m, t.a, z.a, b.c, s.h, [a.e, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['黑霹雷', g.m, t.a, z.c, b.c, s.h, [a.e, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['黑霹雷', g.m, t.a, '异人族：阿提兰崛起', b.c, s.h, [a.e, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['黑霹雷', g.m, t.a, '漫威X', b.c, s.h, [a.e, a.u], [{ for: b.c, type: d.a, value: '65%' }], null, 3],
	['海姆达尔', g.m, t.a, z.B, b.d, s.h, [a.a], [{ for: q.a, type: d.d, value: '36%' }], null, 4],
	['贝塔·雷·比尔', g.m, t.a, z.a, b.d, s.h, [a.k, a.f], [{ for: q.a, type: d.m, value: '60%' }], null, 4],
	['亥伯龙', g.m, t.a, z.c, b.d, s.h, [a.f, a.u, a.H], [{ for: q.a, type: d.a, value: '45%' }], null, 2],
	['亥伯龙', g.m, t.a, z.b, b.d, s.h, [a.f, a.u, a.H], [{ for: q.a, type: d.a, value: '45%' }], null, 2],
	['伊格瑞斯', g.m, t.a, z.a, b.d, s.h, [a.f, a.u, a.H], [{ for: a.H, type: d.a, value: '60%' }], null, 2],
	['地狱风暴', g.m, t.a, z.a, b.a, s.h, [a.l, a.i], [{ for: q.a, type: d.A, value: '50%' }], null, 2],
	['巫毒博士', g.m, t.a, z.a, b.a, s.h, [a.l, a.o], [{ for: q.a, type: d.v, value: '40%' }], null, 2],
	['恶灵骑士（罗比·雷伊斯）', g.m, t.a, z.m, b.a, s.h, [a.e, a.i], [{ for: q.a, type: d.j, value: '50%' }], null, 2],
	['恶灵黑豹', g.m, t.a, z.O, b.a, s.h, [a.g, a.i], [{ for: q.a, type: d.h, value: '15%' }, { for: q.a, type: d.l, value: '30%' }], [{ for: q.a, type: d.l, value: '30%' }, { for: q.a, type: d.G, value: '45%' }, , { for: q.a, type: d.H, value: '15%' },], 2],
	['新星（理查德·赖德）', g.m, t.a, z.a, b.a, s.h, [a.u, a.f], [{ for: s.h, type: d.b, value: '30%' }], [{ for: s.h, type: d.j, value: '25%' }, { for: s.h, type: d.G, value: '40%' }], 2],
	['蔚蓝奇侠', g.m, t.a, '终极战队', b.a, s.h, [a.f, a.u], [{ for: q.a, type: d.d, value: '50%' }], null, 2],
	['诺瓦（萨姆·亚历山大）', g.m, t.a, z.c, '人', s.h, [a.e, a.u], [{ for: q.a, type: d.t, value: '6%' }], null, 2],
	['钢铁神锤', g.m, t.a, z.O, b.d, s.h, [a.m, a.k, a.l], [{ for: q.a, type: d.k, value: '24%' }, { for: q.a, type: d.b, value: '15%' }, { for: q.a, type: d.m, value: '15%' }], null, 2],
	['闹闹', g.m, t.a, z.a, b.a, s.h, [a.g], [{ for: q.a, type: d.B, value: '50%' }], null, 2],
	['惊奇队长', g.f, t.a, z.a, b.a, s.h, [a.e, a.f, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['惊奇队长', g.f, t.a, z.s, b.a, s.h, [a.e, a.f, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['惊奇队长', g.f, t.a, '惊奇女士', b.a, s.h, [a.e, a.f, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['惊奇队长', g.f, t.a, z.M, b.a, s.h, [a.e, a.f, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['惊奇队长', g.f, t.a, z.g, b.a, s.h, [a.e, a.f, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 3],
	['玄武', g.f, t.a, z.a, b.a, s.h, [a.D, a.g, a.h], [{ for: q.a, type: d.k, value: '24%' }], [{ for: a.D, type: d.M, value: '25%' }, { for: a.D, type: d.d, value: '25%' }], 4],
	['美杜莎', g.f, t.a, z.c, b.c, s.h, [a.o], [{ for: t.a, type: d.a, value: '36%' }], null, 4],
	['美杜莎', g.f, t.a, '怪兽出笼！（MFF变体）', b.c, s.h, [a.o], [{ for: t.a, type: d.a, value: '42%' }], null, 4],
	['美杜莎', g.f, t.a, '异人族vsX战警', b.c, s.h, [a.o], [{ for: t.a, type: d.a, value: '45%' }], [{ for: b.c, type: d.G, value: '45%' }], 4],
	['克丽', g.f, t.a, z.a, b.d, s.h, [a.l, a.e], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['奇点', g.f, t.a, z.r, b.d, s.h, [a.e, a.u], [{ for: q.a, type: d.b, value: '30%' }], null, 2],
	['安吉拉', g.f, t.a, z.a, b.d, s.h, [a.n], [{ for: q.a, type: d.e, value: '30%' }], null, 2],
	['安吉拉', g.f, t.a, z.n, b.d, s.h, [a.n], [{ for: q.a, type: d.e, value: '30%' }], null, 2],
	['安吉拉', g.f, t.a, z.c, b.d, s.h, [a.n, a.i], [{ for: q.a, type: d.e, value: '30%' }], null, 2],
	['帕罗·威尔', g.f, t.a, z.a, b.d, s.h, [a.u, a.f], [{ for: q.a, type: d.f, value: '50%' }], [{ for: t.a, type: d.a, value: '30%' }, { for: t.a, type: d.I, value: '25%' }, { for: t.a, type: d.J, value: '15%' }], 2],
	['萨塔娜', g.f, t.a, z.a, b.a, s.h, [a.l, a.i], [{ for: q.a, type: d.l, value: '60%' }], null, 2],
	['萨塔娜', g.f, t.a, '漫威遗产', b.a, s.h, [a.l, a.i], [{ for: q.a, type: d.l, value: '70%' }], null, 2],
	['雷神索尔（简·福斯特）', g.f, t.a, z.c, b.a, s.h, [a.k, a.e], [{ for: q.a, type: d.B, value: '50%' }, { for: q.a, type: d.r, value: '6%' }], null, 2],
	['魁萨（艾薇儿·金凯德）', g.f, t.a, z.c, b.a, s.h, [a.b, a.u], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['分子人', g.m, t.a, z.a, b.a, s.f, [a.e, a.u], [{ for: q.a, type: d.Z, value: '无视己方阵营与敌方阵营之间互相造成的伤害量增减效果%' }, { for: q.a, type: d.L, value: '15%' }, { for: q.a, type: d.W, value: '移除所有减益' }], [{ for: q.a, type: d.O, value: '50%' }], 3],
	['多玛姆', g.m, t.a, z.b, b.f, s.f, [a.l, a.r], [{ for: q.a, type: d.d, value: '24%' }], null, 3],
	['多玛姆', g.m, t.a, '天谴', b.f, s.f, [a.l, a.r], [{ for: s.f, type: d.w, value: '60%' }], null, 3],
	['灭霸', g.m, t.a, z.N, b.d, s.f, [a.C, a.p, a.r], [{ for: s.f, type: d.a, value: '36%' }, { for: s.f, type: d.d, value: '36%' }, { for: s.f, type: d.i, value: '30%' }], null, 3],
	['灭霸', g.m, t.a, z.t, b.d, s.f, [a.C, a.p, a.r], [{ for: s.f, type: d.a, value: '36%' }, { for: s.f, type: d.d, value: '36%' }, { for: s.f, type: d.i, value: '30%' }], null, 3],
	['灭霸', g.m, t.a, z.f, b.d, s.f, [a.C, a.p, a.r], [{ for: s.f, type: d.a, value: '36%' }, { for: s.f, type: d.d, value: '36%' }, { for: s.f, type: d.i, value: '30%' }], null, 3],
	['灭霸', g.m, t.a, z.g, b.d, s.f, [a.C, a.p, a.r], [{ for: s.f, type: d.a, value: '36%' }, { for: s.f, type: d.d, value: '36%' }, { for: s.f, type: d.i, value: '30%' }], null, 3],
	['纳尔', g.m, t.a, z.a, b.d, s.f, [a.t, a.a, a.r], [{ for: a.t, type: d.a, value: '60%' }], null, 3],
	['邪神洛基', g.m, t.a, z.d, b.d, s.f, [a.c, a.j], [{ for: q.a, type: d.z, value: '50%' }], null, 3],
	['邪神洛基', g.f, t.a, '洛基女士', b.d, s.f, [a.c, a.j], [{ for: q.a, type: d.z, value: '50%' }], null, 3],
	['邪神洛基', g.f, t.a, z.B, b.d, s.f, [a.c, a.j], [{ for: q.a, type: d.z, value: '50%' }], null, 3],
	['邪神洛基', g.f, t.a, z.b, b.d, s.f, [a.c, a.j], [{ for: q.a, type: d.z, value: '50%' }], null, 3],
	['邪神洛基', g.f, t.a, '阿斯加德特工', b.d, s.f, [a.c, a.j], [{ for: q.a, type: d.z, value: '50%' }], null, 3],
	['亡刃黑鸦', g.m, t.a, z.N, b.d, s.f, [a.g, a.e], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['亡刃黑鸦', g.m, t.a, z.f, b.d, s.f, [a.g, a.e], [{ for: q.a, type: d.k, value: '24%' }], null, 2],
	['反物质人', g.m, t.a, z.c, b.a, s.f, [a.e, a.u], [{ for: q.a, type: d.a, value: '45%' }], null, 2],
	['塞恩', g.m, t.a, z.a, b.c, s.f, [a.a, a.p, a.r], null, null, 2],
	['奥创', g.m, t.a, z.a, b.f, s.f, [a.m, a.r], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['奥创原始', g.m, t.a, z.e, b.f, s.f, [a.m, a.r], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['奥创马克1', g.m, t.a, z.e, b.f, s.f, [a.m, a.r], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['奥创马克3', g.m, t.a, z.e, b.f, s.f, [a.m, a.r], [{ for: q.a, type: d.a, value: '24%' }], null, 2],
	['毁灭博士', g.m, t.a, z.a, b.a, s.f, [a.r, a.l], [{ for: q.a, type: d.W, value: '移除所有减益（12秒）cd20秒' }], null, 2],
	['罗南', g.m, t.a, z.z, b.d, s.f, [a.s, a.o], [{ for: t.a, type: d.a, value: '36%' }, { for: t.a, type: d.d, value: '36%' }], [{ for: q.a, type: d.j, value: '20%' }], 2],
	['罗南', g.m, t.a, '湮灭', b.d, s.f, [a.s, a.o], [{ for: t.a, type: d.a, value: '36%' }, { for: t.a, type: d.d, value: '36%' }], [{ for: q.a, type: d.j, value: '20%' }], 2],
	['罗南', g.m, t.a, z.M, b.d, s.f, [a.s, a.o], [{ for: t.a, type: d.a, value: '50%' }, { for: t.a, type: d.d, value: '36%' }], [{ for: q.a, type: d.j, value: '20%' }], 2],
	['黑矮星', g.m, t.a, z.N, b.d, s.f, [a.a, a.p], null, null, 2],
	['黑矮星', g.m, t.a, z.f, b.d, s.f, [a.a, a.p], null, null, 2],
	['黑舌谋士', g.m, t.a, z.a, z.N, s.f, [a.r, d.z, a.e], [{ for: q.a, type: d.b, value: '40%' }], null, 2],
	['黑舌谋士', g.m, t.a, z.f, z.N, s.f, [a.r, d.z, a.e], [{ for: q.a, type: d.b, value: '40%' }], null, 2],
	['威勇大将', g.f, t.a, z.a, b.a, s.f, [a.e, a.u], [{ for: q.a, type: d.a, value: '35%' }, { for: '毁灭博士', type: d.b, value: '25%' }, { for: '毁灭博士', type: d.M, value: '20%' }], [{ for: q.a, type: d.g, value: '30%' }], 2],
	['摩根勒菲', g.f, t.a, z.a, b.a, s.f, [a.l, a.r], [{ for: q.a, type: d.i, value: '24%' }], null, 2],
	['暗夜比邻星', g.f, t.a, z.N, b.d, s.f, [a.g, a.e], [{ for: q.a, type: d.j, value: '40%' }, { for: q.a, type: d.r, value: '18%' }], null, 2],
	['暗夜比邻星', g.f, t.a, z.f, b.d, s.f, [a.g, a.e], [{ for: q.a, type: d.j, value: '40%' }, { for: q.a, type: d.r, value: '18%' }], null, 2],
	['死亡女神', g.f, t.a, z.a, b.d, s.f, [a.o, a.r], [{ for: q.a, type: d.b, value: '45%' }], null, 2],
	['死亡女神', g.f, t.a, z.B, b.d, s.f, [a.o, a.r], [{ for: q.a, type: d.b, value: '45%' }], [{ for: q.a, type: d.w, value: '15%' }, { for: q.a, type: d.F, value: '15%' }], 2],
	['超巨星', g.f, t.a, z.a, b.d, s.f, [a.c, a.s], [{ for: q.a, type: d.W, value: '移除所有减益（20秒）cd25秒' }], null, 2],
	['毁灭者', g.t, t.a, z.b, b.e, s.z, [a.i], [{ for: q.a, type: d.f, value: '30%' }], null, 2],
	['毁灭者', g.t, t.a, '普罗米修斯', b.e, s.z, [a.u], [{ for: q.a, type: d.f, value: '30%' }], null, 2]
];